In [3]:
import numpy as np
import matplotlib.pyplot as plt
import modern_robotics as mr

PI = np.pi

In [12]:
# Define the joint screw axes
Slist = np.array([[0, 0, 0],
                  [0, 1, 1],
                  [1, 0, 0],
                  [0, -0.0145, -0.09026],
                  [0, 0, 0],
                  [0, 0, 0]])

Blist = np.array([[0, 0, 0],
                  [0, 1, 1],
                  [1, 0, 0],
                  [0, 0.1201, 0.0455],
                  [-0.0058, 0, 0],
                  [0.0009, 0, 0]])

# Define the home configuration
M = np.array([[1, 0, 0, 0.0009],
                [0, 1, 0, 0.0073],
                [0, 0, 1, 0.1320],
                [0, 0, 0, 1]])


In [23]:

def control(theta, V): 
    # theta: current joint angles
    # V: desired end-effector twist in the space frame
    # return: joint velocities to achieve the desired end-effector twist

    # transform the end-effector twist to the body frame
    T_se = mr.FKinBody(M, Blist, theta)
    T_se_inv = mr.TransInv(T_se)
    V_e = mr.Adjoint(T_se_inv) @ V

    # only care about x,y,z so get rid of the first 3 rows
    V_e = V_e[3:]

    J = mr.JacobianBody(Blist, theta)
    
    # only care about x,y,z so get rid of the first three rows
    J = J[3:,:]
    J_inv = np.linalg.pinv(J)

    theta_dot = J_inv @ V_e
    return theta_dot

In [24]:
theta = np.array([0, 0.8, PI/2])
T_se_initial = mr.FKinSpace(M, Slist, theta)
pos = T_se_initial[:3, 3]

desired_pos = np.array([0.1, 0, 0]) # desired end-effector position: 100mm in x-axis

linear_twist = desired_pos - pos # 3 vector linear twist in the space frame

V_d = np.array([0, 0, 0, linear_twist[0], linear_twist[1], linear_twist[2]]) # desired end-effector twist

for i in range(100):
    theta_dot = control(theta, V_d)
    theta = theta + theta_dot * 0.01
    T_se = mr.FKinSpace(M, Slist, theta)
    pos = T_se[:3, 3]
    print(pos)






[0.08296997 0.00722374 0.03635133]
[0.08315802 0.00714746 0.03598945]
[0.08334595 0.00707118 0.03562738]
[0.08353376 0.00699488 0.03526512]
[0.08372145 0.00691858 0.03490267]
[0.08390902 0.00684227 0.03454002]
[0.08409647 0.00676595 0.03417719]
[0.08428379 0.00668963 0.03381417]
[0.08447098 0.0066133  0.03345096]
[0.08465805 0.00653696 0.03308756]
[0.08484499 0.00646061 0.03272398]
[0.0850318  0.00638426 0.03236021]
[0.08521848 0.0063079  0.03199625]
[0.08540503 0.00623153 0.03163211]
[0.08559144 0.00615517 0.03126778]
[0.08577771 0.00607879 0.03090327]
[0.08596385 0.00600241 0.03053857]
[0.08614985 0.00592603 0.03017369]
[0.08633572 0.00584965 0.02980863]
[0.08652144 0.00577326 0.02944339]
[0.08670702 0.00569687 0.02907797]
[0.08689245 0.00562047 0.02871236]
[0.08707775 0.00554408 0.02834658]
[0.08726289 0.00546768 0.02798061]
[0.0874479  0.00539128 0.02761447]
[0.08763275 0.00531488 0.02724814]
[0.08781746 0.00523848 0.02688164]
[0.08800201 0.00516208 0.02651496]
[0.08818642 0.005085